FROM node:12-alpine

ARG MAINTAINER_EMAIL
ARG SSL_SUBJECT

COPY src/ /src
COPY package*.json /src/

WORKDIR /src

RUN npm install

RUN npx greenlock init --config-dir ./greenlock.d --maintainer-email $MAINTAINER_EMAIL
RUN npx greenlock add  --subject ${SSL_SUBJECT}   --altnames $SSL_SUBJECT

EXPOSE 443

CMD ["node", "index.js"]
