classDiagram
    class reverse_proxy {
        <<Service>> 
        http://localhost:8000
    }
    class front_end {
        <<Service>>
        http://front-end:3000 
    }
    class orchestration {
        <<Service>>
        http://orchestration:3001
        AI API
        Voice service API
    }
    class ibm_watson {
        <<External API>>
    }
    class voice_service {
        <<Service>>
        http://voice-service:8081
        Voice cache
    }
    class mouth_shapes {
        <<Service>>
        http://mouth-shapes:3005
        tts audio download
        Mouth shapes analysis
    }
    class text_to_speech {
        <<Service>>
        http://tts:59125
    }
    reverse_proxy -- front_end
    reverse_proxy -- orchestration
    orchestration -- ibm_watson
    orchestration -- voice_service
    voice_service .. text_to_speech: API knowledge
    text_to_speech -- mouth_shapes
    voice_service -- mouth_shapes
    voice_service -- reverse_proxy: tts audio proxy
